[package]
name = "waveplot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcd = "0.6.1"
clap = { version = "4.3.11", features = ["derive"] }
tui = "0.19.0"
env_logger = "0.10.0"
log = "0.4.19"
